mysite/app1/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('employee/<int:pk>', views.EmployeeDetailView.as_view(), name='employee-detail'),
    path('employees/', views.EmployeeListView.as_view(), name='employees'),
    path('add_new/', views.add_new, name='add_new'),
    path('calculate/', views.calculate, name='calculate'),
    path('results/', views.results, name='results'),
    path('added/', views.added, name='added'),
    path('dependents/', views.add_dependents, name='dependents'),
    path('employee_search/', views.employee_search, name='employee_search'),
    path('delete_dependent/', views.delete_dependent, name='delete_dependent'),
    path('help/', views.help, name='help'),
    path('remove_employee/', views.remove_employee, name='remove_employee'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/app1/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from decimal import Decimal
from django.conf import settings

class Company(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    base_salary = models.DecimalField(max_digits=9, decimal_places=2)
    #Standard deduction for employees
    emp_deduct = models.DecimalField(max_digits=6, decimal_places=2)
    #Standard deduction for dependents
    dep_deduct = models.DecimalField(max_digits=6, decimal_places=2)
    company_name = models.CharField(max_length=30)
    #Character code for discount policy
    discount_policy = models.CharField(max_length=1)
    #Discount percentage for qualifying employees/dependents
    discount_percentage = models.DecimalField(default=0,max_digits=6, decimal_places=2)
    #Percentage that company pays for benefits
    contribution_percent = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.company_name


class Employee(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    salary = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return self.first_name+" "+self.last_name

    def get_absolute_url(self):
        #Returns the url to access a detail record for this employee.
        return reverse('employee-detail', args=[str(self.id)])

    class Meta:
         unique_together = ('first_name', 'last_name',)


class Dependent(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    f_name = models.CharField(max_length=30)
    l_name = models.CharField(max_length=30)
    birth_date = models.DateField()

    def get_deduction(self, company):
        discount_per = Decimal(0)
        deduction = company.dep_deduct
        #check for discount
        if company.discount_policy.lower() == self.f_name[0].lower():
            discount_per = company.discount_percentage
        discount = ((discount_per/100)*deduction)
        deduction = deduction -discount

        return deduction

    def __str__(self):
        return self.f_name +' '+ self.l_name

mysite/app1/forms.py
from django import forms
from .models import Company, Employee, Dependent
from django.forms import ModelForm

#Form for quick calculation
class CalcForm(forms.Form):
    emp_salary = forms.CharField(label='Salary')
    base_deduction = forms.CharField(label='Employee Cost')
    dependents = forms.CharField(label='Number of Dependents')
    dependent_deduction = forms.CharField(label= 'Dependent Cost')
    discount = forms.CharField(label='Discount Percentage')
    num_eligible = forms.CharField(label ='Discount eligible dependents')
    co_pays = forms.CharField(label ='Percentage Paid by Employer')
    emp_eligible = forms.BooleanField(label= 'Employee eligible for discount?', required=False)


#Form for adding new employees
class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        labels ={
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'salary': 'Annual Salary',
        }
        fields = ['first_name', 'last_name', 'salary']


#Form for modifying employee info
class EmployeeMod(ModelForm):
    class Meta:
        model = Employee
        fields = ['last_name', 'salary']


#Add dependents
class DependentForm(ModelForm):
    class Meta:
        model = Dependent
        labels = {
            'f_name': 'First Name',
            'l_name': 'Last Name',
            'birth_date': 'Birth Date (mm/dd/yyyy)',
        }
        fields = ['f_name', 'l_name', 'birth_date']


#Search database for employee
class SearchForm(forms.Form):
    full_name = forms.CharField(label ='Full Name')

mysite/app1/views.py
from django.shortcuts import render,  get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.views import generic
from .models import Employee, Company, Dependent
from .forms import CalcForm, EmployeeForm, DependentForm, SearchForm, EmployeeMod
from django.db.models import Q
from django.urls import reverse
from decimal import Decimal
import locale
from django.http import HttpResponseRedirect

#set locale for currency formatting
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

#Home page
def index(request):
    #Demo basic use of session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)


#login function for employers
def login(request):
    return render(request, 'login.html')


#allow employers to add new employees
@login_required
def add_new(request):
    #if POST request, process input
    if request.method == 'POST':
        ##get user company to populate employee company
        user = request.user
        company_query = Company.objects.filter(user = user.id)
        #if user doesn't belong to a company
        if not company_query:
            error_msg = "Error: you don't belong to a company"
            target = 'employees'
            return error_page(request, error_msg, target)
        #get company id
        company_id = company_query[0].pk
        #get form input
        employee_form = EmployeeForm(request.POST)
        #validate form input
        if employee_form.is_valid():
            temp = employee_form.save(commit=False)
            temp.company_id = company_id
            temp.first_name = temp.first_name.lower()
            temp.last_name = temp.last_name.lower()
            temp.save()
            emp_id = temp.pk
            request.session['last_accessed'] = emp_id;
            #specify employee string so we can reuse added.html
            type_added = 'Employee'
            context = {
                'type_added': type_added,
            }
            return render(request, 'added.html', context=context)
        #If user attempts to add duplicate first and last name
        else:
            error_msg = "Error: employee is already in the database"
            target = 'add_new'
            return error_page(request, error_msg, target)
    #create blank form
    else:
        employee_form = EmployeeForm()
        return render(request, 'add_new.html', {'employee_form': employee_form})


#Allow users to remove employees
def remove_employee(request):
    if request.method == 'POST':
        emp_id = request.POST.get('delete', "")
        Employee.objects.filter(pk=emp_id).delete()
        return HttpResponseRedirect(reverse('employees'))
    else:
        #This shouldn't happen, I had to try to be funny somewhere
        error_msg = "Error: delete failed, it's your fault"
        return render(request, 'error.html', {'error_msg': error_msg})


#Helper error message function used by multiple views
def error_page(request, error_msg, target):
    context = {
        'error_msg': error_msg,
        'target': target,
    }
    return render(request, 'error.html', context)


#Allows the user to search for a specific employee
def employee_search(request):
    #Get first and last name
    full_name = request.POST.get('full_name').split()
    employee_set = None
    failed  = False
    #If two or more strings were entered
    if len(full_name) > 1:
        f_name = full_name[0]
        l_name = full_name[1]
        #Checks the first two keywords against first and
        #last names in the database ignores any subsequent input
        employee_set = Employee.objects.filter(Q(first_name__icontains = f_name) | Q(last_name__icontains = l_name)
        |Q(first_name__icontains = l_name) | Q(last_name__icontains = f_name))
    #If only first or last name was entered, we will list any matches to either
    elif len(full_name) >0:
        f_name = full_name[0]
        employee_set = Employee.objects.filter( Q(first_name__icontains = f_name) | Q(last_name__icontains = f_name))
    #If filter failed
    if employee_set is None or len(employee_set) ==0:
        failed = True
    context = {
            'failed': failed,
            'employee_set': employee_set,
    }
    return render(request, 'search_results.html', context)


#Let user know adding employee was successful
@login_required
def added(request):
    return render(request, 'added.html')


#Allows the user to add depdndents after adding an employee
@login_required
def add_dependents(request):
    emp_id = request.session['last_accessed']
    employee = Employee.objects.get(pk=emp_id)

    if request.method == 'POST':
        dependent_form = DependentForm(request.POST)
        if dependent_form.is_valid():
            temp = dependent_form.save(commit=False)
            temp.employee_id = emp_id
            temp.save()
            type_added = 'Dependent'
            context = {
                'type_added': type_added
            }
            return render(request, 'added.html', context=context)
        #If form input is invlaid
        else:
            error_msg = "Error: Please enter date in the specified format."
            target = 'dependents'
            return error_page(request, error_msg, target)
    else:
        dependent_form = DependentForm()
        context = {
            'employee': employee,
            'dependent_form': dependent_form,
        }
        return render(request, 'dependents.html', context=context)


#Allows users to delete dependents
@login_required
def delete_dependent(request):
    if request.method == 'POST':
        dependent = request.POST.get('delete', "")
        Dependent.objects.filter(pk=dependent).delete()
        #Get the url
        emp_id = str(request.session['last_accessed'])
        employee = Employee.objects.get(pk=emp_id)
        url = employee.get_absolute_url()

        return redirect( url)
    else:
        #This shouldn't happen, I had to try to be funny somewhere
        error_msg = "Error: delete failed, it's your fault"
        return render(request, 'error.html', {'error_msg': error_msg})


#Deduction calculator form page
def calculate(request):
    calc_form = CalcForm()
    return render(request, 'calculate.html', {'calc_form': calc_form})


#Deduction calculator logic, redirects to results page
def results(request):
    try:
        #this employee's salary
        salary = float(request.POST.get('emp_salary'))
        #base deduction
        base_deduct= float(request.POST.get('base_deduction'))
        #number of dependents
        dep = float(request.POST.get('dependents'))
        #dependent deduction
        dep_deduct = float(request.POST.get('dependent_deduction'))
        #discount percentage
        discount = float(request.POST.get('discount'))/100
        #number of dependents eligible for discount
        num_eligible = float(request.POST.get('num_eligible'))
        #percentage of benefit cost that employer pays
        co_pays = float(request.POST.get('co_pays'))/100
        #True if employee is eligible for discount
        emp_eligible = request.POST.get('emp_eligible')
        #calculate deduction
        deduction =0
    except:
        error_msg = "Invalid input, see help page for more info."
        target = 'calculate'
        return error_page(request, error_msg, target)
    #Calculate deduction
    if emp_eligible == True:
        deduction = base_deduct - (discount*base_deduct)
    else:
        deduction = base_deduct
    if dep > 0 and num_eligible > 0:
        deduction += (dep - num_eligible) * dep_deduct + num_eligible * (dep_deduct - (discount * dep_deduct))
    else:
        deduction += dep*dep_deduct
    company_pays = co_pays*deduction
    deduction -= company_pays
    #salary after deduction
    after_deduction = float(salary)-deduction
    #formatted context values to display on results page
    context = {
        'salary': locale.currency( salary, grouping=True ),
        'dep': int(dep),
        'deduction': locale.currency(deduction, grouping=True ),
        'after_deduction': locale.currency(after_deduction, grouping=True ),
        'company_pays': locale.currency(company_pays, grouping=True ),
    }
    return render(request, 'results.html', context)


#Help page
def help(request):
    return render(request, 'help.html')


#List of employees for the company that the user represents
class EmployeeListView(LoginRequiredMixin, generic.ListView):
    #Keeps people from accessing this page with the url
    #redirects to login page if they try
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Employee
    #this forces pagination, 10 employees per page
    paginate_by = 10

    def get_queryset(self):
        #get logged in user
        user = self.request.user
        #get company with fk reference to this user
        company_query = Company.objects.filter(user = user.id)
        #If this user belongs to a company
        if company_query:
            return Employee.objects.filter(company=company_query[0])
        else:
            return Employee.objects.all()


#employee details
class EmployeeDetailView(FormMixin, LoginRequiredMixin, generic.DetailView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Employee
    form_class = EmployeeMod

    #Get this employee's url
    def get_success_url(self):
        return reverse('employee-detail', kwargs={'pk': self.object.id})


    #Add a little to the context and session
    def get_context_data(self, **kwargs):
        #Keep track of current employee in session
        self.request.session['last_accessed'] =self.kwargs['pk']

mysite/app1/templates/app1/employee_detail.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h1> Details for Employee: {{employee.first_name.capitalize}} {{employee.last_name.capitalize}}</h1>
<h2> Company: {{company_name}}</h2>
<table  class= 'pure-table pure-table-horizontal'>
  <th> Description</th>
  <th> Result </th>
  <tbody>
    <tr>
      <td> Employee Name: </td>
      <td> {{employee.first_name.capitalize}} {{employee.last_name.capitalize}} </td>
    </tr>

    <tr>
      <td> Employee ID: </td>
      <td> {{employee.id}} </td>
    </tr>

    <tr>
      <td> Employee Salary: </td>
      <td> {{salary}} </td>
    </tr>

    <tr>
      <td> Total Benefit Cost: </td>
      <td> {{total_cost}} </td>
    </tr>

    <tr>
      <td> Employee Annual Deduction: </td>
      <td> {{deduction}} </td>
    </tr>

    <tr>
      <td> Deduction Per Paycheck: </td>
      <td> {{check_deduction}} </td>
    </tr>

    <tr>
      <td> Percentage Paid By Employer </td>
      <td> {{company_percent}} </td>
    </tr>

    <tr>
      <td> Employer Annual Cost: </td>
      <td> {{employer_cost}} </td>
    </tr>

  </tbody>
</table>

<button onclick="showForm()" class = "pure-button" id="detail_button" >Edit Employee</button>

<div id="modify" style="display: none;">
  <h3> Edit Employee Information </h3>
	<form method="POST" class="pure-form pure-form-aligned">
	  {% csrf_token %}
	  {{ form|crispy  }}
	  <button type="submit" class = "pure-button" id="detail_button" >Update Values</button>
	</form>
</div>

{% if employee.dependent_set.all  %}
  <h1> Dependents </h1>
  <table class='pure-table pure-table-horizontal'>
    <th> Name</th>
    <th> Birth Date </th>
    <th> Remove </th>
    {% for d in employee.dependent_set.all  %}
	    <tr>
        <td> Name: {{ d }}  </td>
		    <td>Birth Date: {{ d.birth_date }}</td>
        <td>
		      <form method="post" class="pure-form pure-form-aligned" action="{% url 'delete_dependent' %}">
			      {% csrf_token %}
			      <button type="submit" id='delete' value={{ d.pk }} name='delete' onclick="return confirm('Are you sure?')">Remove</button>
		      </form>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endif %}

<form method="get" class="pure-form pure-form-aligned" action="{% url 'dependents' %}">
  {% csrf_token %}
  <button type="submit" class = "pure-button" id="detail_button" >Add Dependent</button>
</form>

<br> </br>

<script>
function showForm() {
    var x = document.getElementById("modify");
    if (x.style.display === "block") {
        x.style.display = "none";
    } else {
        x.style.display = "block";
    }
}
</script>
{% endblock %}
<!-- ex: set tabstop=2 expandtab: -->

mysite/app1/templates/app1/employee_list.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h1>{{user.groups.all.0}} Employees </h1>
{% if employee_list %}
  <table class='pure-table pure-table-horizontal'>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Details</th>
    <th>Remove</th>
    {% for employee in employee_list %}
      <tr>
        <td>{{employee.first_name.capitalize}}</td>
        <td>{{employee.last_name.capitalize}}</td>
        <td>
          <a href="{{ employee.get_absolute_url }}"><button>Details</button></a>
        </td>
        <td>
          <form method="post" class="pure-form pure-form-aligned" id='delete' action="{% url 'remove_employee' %}">
			      {% csrf_token %}
			      <button type="submit" value={{ employee.pk }} name='delete' onclick="return confirm('Are you sure?')">Remove</button>
		      </form>
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>There are no Employees in the database.</p>
{% endif %}
<br></br>
<a href="{% url 'add_new' %}"><button class = "pure-button">Add New Employee</button></a>
<br></br>
<p><strong>Search Employees by Name</strong></p>
<form method="post" class="pure-form pure-form-aligned" action="{% url 'employee_search' %}">
  {% csrf_token %}
	<input id="full_name" type="text" name="full_name">
	<br></br>
  <input type="submit" value="Search">
</form>

{% endblock %}
<!-- ex: set tabstop=2 expandtab: -->